### PR TITLE
fix bar beta-eta clash and alg comments

### LINKED ISSUE #13: algpseudocode comments break
Hi! Thanks for the great package. `algpseudocode` comments aren't working for me. The following breaks

```tex
\begin{algorithmic}
\State $i \gets 10$ \Comment{hi}
\end{algorithmic}
```

The log shows

`Environment align* undefined. \State $i \gets 10$ \Comment{hi}`

### PR DESCRIPTION
**Pull request by miguelbiron**
fixes #13 and #14

### CODE REVIEW

**Comment by trevorcampbell** [comment]
This looks good to me, thanks @miguelbiron . 

@jhuggins @jnegrea can I just get one more set of eyes on this before merging? If you're happy with it you can go ahead and merge.

**Comment by miguelbiron** [comment]
To your question, I found an old copy of tchdr.sty in Gary's repos. The old convention was `\boldeta`. Not sure what you think of it but to me it suggests a bold eta.

https://github.com/garyzhubc/tchdr/blob/7d7df3726f2a422eb52d8bfbc5690e5f39cdda36/tchdr.sty#L542

**Comment by trevorcampbell** [comment]
I'd be OK with two solutions:
- for `\eta`, just implement the two explicitly: `\bareta` and `\boldeta`
- some joint command like `\bobeta` to do `\boldorbar`

**Comment by miguelbiron** [comment]
Ok I went with the first option because it seemed like the least disruptive.

**Review by jnegrea — APPROVED** [review]

**Comment by jnegrea** [comment]
The fix looks fine, and I like having both bold and bar defined separately. I was thinking for a moment that we should have a version that is \boldorbareta so that it changes to whatever convention \boldorbar is set to, but then I rethought that since it is maybe redundant as it doesn't save many characters relative to \boldorbar{\eta}

**Comment by trevorcampbell** [comment]
Thanks @miguelbiron . Merged!

**Pull request merged**
